version: '3.8'

services:
  coolify:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: coolify
    restart: always
    environment:
      - APP_ENV=production
      - APP_KEY=${COOLIFY_APP_KEY}
      - APP_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}
      - APP_PORT=8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/storage/app/coolify.sqlite
      - REDIS_HOST=coolify-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_HOST=coolify-soketi
      - PUSHER_PORT=6001
      - PUSHER_SCHEME=http
      - COOLIFY_PROXY_DISABLED=true
      - COOLIFY_DEFAULT_NETWORK=proxy_network
      - COOLIFY_INSTANCE_ID=${COOLIFY_INSTANCE_ID}
      - COOLIFY_WHITE_LABEL=false
      - COOLIFY_AUTO_UPDATE=false
    volumes:
      - ./storage:/var/www/html/storage
      - ./backups:/var/www/html/backups
      - ./ssh:/var/www/html/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - coolify_internal
      - proxy_network
    depends_on:
      - coolify-redis
      - coolify-soketi
    user: "9999:9999"

  coolify-redis:
    image: redis:7-alpine
    container_name: coolify-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coolify_internal

  coolify-soketi:
    image: quay.io/soketi/soketi:1.6-16-alpine
    container_name: coolify-soketi
    restart: always
    environment:
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
      - SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES=true
    networks:
      - coolify_internal

  coolify-queue:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: coolify-queue
    restart: always
    command: php artisan horizon
    environment:
      - APP_ENV=production
      - APP_KEY=${COOLIFY_APP_KEY}
      - APP_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/storage/app/coolify.sqlite
      - REDIS_HOST=coolify-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_HOST=coolify-soketi
      - PUSHER_PORT=6001
      - PUSHER_SCHEME=http
      - COOLIFY_PROXY_DISABLED=true
      - COOLIFY_DEFAULT_NETWORK=proxy_network
    volumes:
      - ./storage:/var/www/html/storage
      - ./ssh:/var/www/html/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - coolify_internal
      - proxy_network
    depends_on:
      - coolify-redis
      - coolify-soketi
    user: "9999:9999"

networks:
  coolify_internal:
  proxy_network:
    external: true