version: '3.8'

services:
  coolify-db:
    image: postgres:16-alpine
    container_name: coolify-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coolify_internal

  coolify-redis:
    image: redis:7-alpine
    container_name: coolify-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coolify_internal

  coolify-soketi:
    image: quay.io/soketi/soketi:1.6-16-alpine
    container_name: coolify-soketi
    restart: always
    environment:
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
      - SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES=true
    networks:
      - coolify_internal

  coolify-init:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: coolify-init
    command: sh -c "php artisan migrate --force && php artisan db:seed --force || true"
    environment:
      - APP_ENV=production
      - APP_KEY=${COOLIFY_APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=coolify-db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=coolify-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    volumes:
      - ./coolify/storage:/var/www/html/storage
    networks:
      - coolify_internal
    depends_on:
      coolify-db:
        condition: service_healthy
      coolify-redis:
        condition: service_started
    restart: "no"

  coolify:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: coolify
    restart: always
    environment:
      - APP_ENV=production
      - APP_KEY=${COOLIFY_APP_KEY}
      - APP_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}
      - APP_PORT=8000
      - DB_CONNECTION=pgsql
      - DB_HOST=coolify-db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=coolify-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_HOST=coolify-soketi
      - PUSHER_PORT=6001
      - PUSHER_SCHEME=http
      - COOLIFY_PROXY_DISABLED=true
      - COOLIFY_DEFAULT_NETWORK=proxy_network
      - COOLIFY_INSTANCE_ID=${COOLIFY_INSTANCE_ID}
      - COOLIFY_WHITE_LABEL=false
      - COOLIFY_AUTO_UPDATE=false
    volumes:
      - ./coolify/storage:/var/www/html/storage
      - ./coolify/backups:/var/www/html/backups
      - ./ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - coolify_internal
      - proxy_network
    depends_on:
      coolify-db:
        condition: service_healthy
      coolify-redis:
        condition: service_started
      coolify-soketi:
        condition: service_started
      coolify-init:
        condition: service_completed_successfully

  coolify-queue:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: coolify-queue
    restart: always
    command: php artisan horizon
    environment:
      - APP_ENV=production
      - APP_KEY=${COOLIFY_APP_KEY}
      - APP_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}
      - DB_CONNECTION=pgsql
      - DB_HOST=coolify-db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=coolify-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_HOST=coolify-soketi
      - PUSHER_PORT=6001
      - PUSHER_SCHEME=http
      - COOLIFY_PROXY_DISABLED=true
      - COOLIFY_DEFAULT_NETWORK=proxy_network
    volumes:
      - ./coolify/storage:/var/www/html/storage
      - ./ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - coolify_internal
      - proxy_network
    depends_on:
      coolify-db:
        condition: service_healthy
      coolify-redis:
        condition: service_started
      coolify-soketi:
        condition: service_started
      coolify-init:
        condition: service_completed_successfully

networks:
  coolify_internal:
  proxy_network:
    external: true