services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    depends_on:
      - freescout-db
    volumes:
      - ./data:/data
      - ./logs:/www/logs
    environment:
      - CONTAINER_NAME=freescout-app
      - DB_HOST=freescout-db
      - DB_NAME=${FREESCOUT_DB_NAME}
      - DB_USER=${FREESCOUT_DB_USER}
      - DB_PASS=${FREESCOUT_DB_PASS}
      - SITE_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}
      - ADMIN_EMAIL=${FREESCOUT_ADMIN_EMAIL}
      - ADMIN_PASS=${FREESCOUT_ADMIN_PASS}
      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=FALSE
      - TIMEZONE=${GENERIC_TIMEZONE}
    restart: always
    networks:
      - internal
      - proxy_network

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=${FREESCOUT_DB_ROOT_PASS}
      - DB_NAME=${FREESCOUT_DB_NAME}
      - DB_USER=${FREESCOUT_DB_USER}
      - DB_PASS=${FREESCOUT_DB_PASS}
      - CONTAINER_NAME=freescout-db
    restart: always
    networks:
      - internal

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    depends_on:
      - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=${FREESCOUT_DB_NAME}
      - DB_USER=${FREESCOUT_DB_USER}
      - DB_PASS=${FREESCOUT_DB_PASS}
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
    networks:
      - internal

networks:
  internal:
  proxy_network:
    external: true