services:
  mattermost-db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${MM_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MM_POSTGRES_PASSWORD}
      - POSTGRES_DB=${MM_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MM_POSTGRES_USER} -d ${MM_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mattermost_internal

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    restart: always
    container_name: mattermost
    depends_on:
      mattermost-db:
        condition: service_healthy
    environment:
      - MM_USERNAME=${MM_POSTGRES_USER}
      - MM_PASSWORD=${MM_POSTGRES_PASSWORD}
      - MM_DBNAME=${MM_POSTGRES_DB}
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://${MM_POSTGRES_USER}:${MM_POSTGRES_PASSWORD}@mattermost-db:5432/${MM_POSTGRES_DB}?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=https://${SUBDOMAIN}.${DOMAIN_NAME}
      - MM_SERVICESETTINGS_ENABLECUSTOMEMOJI=true
      - MM_SERVICESETTINGS_ENABLELINKPREVIEWS=true
      - MM_PLUGINSETTINGS_ENABLE=true
      - MM_PLUGINSETTINGS_ENABLEUPLOADS=true
      - MM_EMAILSETTINGS_SENDEMAILS=false
      - MM_LOGSETTINGS_CONSOLELEVEL=INFO
    volumes:
      - mattermost_config:/mattermost/config
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
      - mattermost_client_plugins:/mattermost/client/plugins
      - mattermost_bleve_indexes:/mattermost/bleve-indexes
      - ./data:/mattermost/data/user_uploads
    networks:
      - mattermost_internal
      - proxy_network

volumes:
  postgres_data:
  mattermost_config:
  mattermost_data:
  mattermost_logs:
  mattermost_plugins:
  mattermost_client_plugins:
  mattermost_bleve_indexes:

networks:
  mattermost_internal:
  proxy_network:
    external: true
