services:
  ghost-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${GHOST_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${GHOST_DB_NAME}
      - MYSQL_USER=${GHOST_DB_USER}
      - MYSQL_PASSWORD=${GHOST_DB_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ghost_internal

  ghost:
    image: ghost:5-alpine
    restart: always
    container_name: ghost
    depends_on:
      ghost-db:
        condition: service_healthy
    environment:
      # Database configuration
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=${GHOST_DB_USER}
      - database__connection__password=${GHOST_DB_PASSWORD}
      - database__connection__database=${GHOST_DB_NAME}

      # Ghost configuration
      - url=https://${SUBDOMAIN}.${DOMAIN_NAME}
      - NODE_ENV=production

      # Mail configuration
      - mail__transport=SMTP
      - mail__from=${GHOST_MAIL_FROM}
      - mail__options__host=${GHOST_SMTP_HOST}
      - mail__options__port=${GHOST_SMTP_PORT}
      - mail__options__secure=${GHOST_SMTP_SECURE}
      - mail__options__requireTLS=true
      - mail__options__auth__user=${GHOST_SMTP_USER}
      - mail__options__auth__pass=${GHOST_SMTP_PASSWORD}

    volumes:
      - ./content/data:/var/lib/ghost/content/data
      - ./content/images:/var/lib/ghost/content/images
      - ./content/files:/var/lib/ghost/content/files
      - ./content/themes:/var/lib/ghost/content/themes
      - ./content/adapters:/var/lib/ghost/content/adapters
      - ./content/logs:/var/lib/ghost/content/logs
      - ./content/settings:/var/lib/ghost/content/settings
    networks:
      - ghost_internal
      - proxy_network

networks:
  ghost_internal:
  proxy_network:
    external: true
