services:
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      # Root credentials
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

      # Server configuration
      - MINIO_SERVER_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}
      - MINIO_BROWSER_REDIRECT_URL=https://${SUBDOMAIN_CONSOLE}.${DOMAIN_NAME}

      # Region (optional)
      - MINIO_REGION=${MINIO_REGION}

      # Additional settings
      - MINIO_PROMETHEUS_AUTH_TYPE=public

    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true