services:
  nocodb-db:
    image: postgres:16.6
    container_name: nocodb-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nocodb_internal

  nocodb-redis:
    image: redis:7-alpine
    container_name: nocodb-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - nocodb_internal

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: always
    depends_on:
      nocodb-db:
        condition: service_healthy
      nocodb-redis:
        condition: service_healthy
    environment:
      # Database Configuration (Mandatory)
      - NC_DB=pg://nocodb-db:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}

      # Authentication (Mandatory)
      - NC_AUTH_JWT_SECRET=${NC_AUTH_JWT_SECRET}
      - NC_JWT_EXPIRES_IN=${NC_JWT_EXPIRES_IN}

      # Admin Configuration
      - NC_ADMIN_EMAIL=${NC_ADMIN_EMAIL}
      - NC_ADMIN_PASSWORD=${NC_ADMIN_PASSWORD}

      # Cache Configuration (Mandatory for production)
      - NC_REDIS_URL=redis://:${REDIS_PASSWORD}@nocodb-redis:6379

      # Public URL Configuration
      - NC_PUBLIC_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}

      # Storage Configuration
      - NC_ATTACHMENT_FIELD_SIZE=${NC_ATTACHMENT_FIELD_SIZE}
      - NC_MAX_ATTACHMENTS_ALLOWED=${NC_MAX_ATTACHMENTS_ALLOWED}
      - NC_SECURE_ATTACHMENTS=${NC_SECURE_ATTACHMENTS}
      - NC_ATTACHMENT_EXPIRE_SECONDS=${NC_ATTACHMENT_EXPIRE_SECONDS}

      # Email Configuration
      - NC_SMTP_FROM=${NC_SMTP_FROM}
      - NC_SMTP_HOST=${NC_SMTP_HOST}
      - NC_SMTP_PORT=${NC_SMTP_PORT}
      - NC_SMTP_USERNAME=${NC_SMTP_USERNAME}
      - NC_SMTP_PASSWORD=${NC_SMTP_PASSWORD}
      - NC_SMTP_SECURE=${NC_SMTP_SECURE}

      # Product Configuration
      - NC_INVITE_ONLY_SIGNUP=${NC_INVITE_ONLY_SIGNUP}
      - NC_DISABLE_AUDIT=${NC_DISABLE_AUDIT}
      - NC_TOOL_DIR=/usr/app/data

      # Security
      - NC_CONNECTION_ENCRYPT_KEY=${NC_CONNECTION_ENCRYPT_KEY}
      - NC_SANITIZE_COLUMN_NAME=true
      - NC_ALLOW_LOCAL_HOOKS=false

      # Performance
      - NC_DISABLE_CACHE=false
      - DB_QUERY_LIMIT_DEFAULT=25
      - DB_QUERY_LIMIT_MAX=1000

      # Telemetry
      - NC_DISABLE_TELE=${NC_DISABLE_TELE}

    volumes:
      - ./nocodb/data:/usr/app/data
      - ./nocodb/uploads:/usr/app/uploads
    networks:
      - nocodb_internal
      - proxy_network

networks:
  nocodb_internal:
  proxy_network:
    external: true