services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '${NPM_ADMIN_PORT:-81}:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${NPM_DB_USER}"
      DB_MYSQL_PASSWORD: "${NPM_DB_PASSWORD}"
      DB_MYSQL_NAME: "${NPM_DB_NAME}"
    networks:
      - npm_network
      - proxy_network
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${NPM_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${NPM_DB_NAME}"
      MYSQL_USER: "${NPM_DB_USER}"
      MYSQL_PASSWORD: "${NPM_DB_PASSWORD}"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - npm_network

networks:
  npm_network:
    internal: true
  proxy_network:
    name: proxy_network
    external: true